-------------------------------------------------------------------------------
Test set: signature_generator.example.signature_generator.controller.AuthControllerTest
-------------------------------------------------------------------------------
Tests run: 10, Failures: 3, Errors: 2, Skipped: 0, Time elapsed: 0.152 s <<< FAILURE! -- in signature_generator.example.signature_generator.controller.AuthControllerTest
signature_generator.example.signature_generator.controller.AuthControllerTest.shouldReturnErrorWhenRegisteringWithExistingEmail -- Time elapsed: 0.011 s <<< FAILURE!
Wanted but not invoked:
userService.registerUser(
    "existinguser",
    "password123",
    "existing@example.com",
    "1234567890"
);
-> at signature_generator.example.signature_generator.auth.service.UserService.registerUser(UserService.java:22)

However, there was exactly 1 interaction with this mock:
userService.registerUser(
    "existing@example.com",
    "password123",
    "existing@example.com",
    "1234567890"
);
-> at signature_generator.example.signature_generator.auth.controller.AuthController.register(AuthController.java:36)


	at signature_generator.example.signature_generator.auth.service.UserService.registerUser(UserService.java:22)
	at signature_generator.example.signature_generator.controller.AuthControllerTest.shouldReturnErrorWhenRegisteringWithExistingEmail(AuthControllerTest.java:94)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

signature_generator.example.signature_generator.controller.AuthControllerTest.shouldSuccessfullyRegisterNewUserWithValidInformation -- Time elapsed: 0.004 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <testuser> but was: <test@example.com>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
	at signature_generator.example.signature_generator.controller.AuthControllerTest.shouldSuccessfullyRegisterNewUserWithValidInformation(AuthControllerTest.java:65)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

signature_generator.example.signature_generator.controller.AuthControllerTest.shouldGenerateAndReturnJwtTokenUponSuccessfulLogin -- Time elapsed: 0.003 s <<< ERROR!
org.mockito.exceptions.misusing.PotentialStubbingProblem: 

Strict stubbing argument mismatch. Please check:
 - this invocation of 'buildToken' method:
    jwtService.buildToken(
    "test@example.com",
    1L
);
    -> at signature_generator.example.signature_generator.auth.controller.AuthController.login(AuthController.java:126)
 - has following stubbing(s) with different arguments:
    1. jwtService.buildToken("testuser", 1L);
      -> at signature_generator.example.signature_generator.controller.AuthControllerTest.shouldGenerateAndReturnJwtTokenUponSuccessfulLogin(AuthControllerTest.java:282)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at signature_generator.example.signature_generator.auth.service.JwtService.buildToken(JwtService.java:26)
	at signature_generator.example.signature_generator.auth.controller.AuthController.login(AuthController.java:126)
	at signature_generator.example.signature_generator.controller.AuthControllerTest.shouldGenerateAndReturnJwtTokenUponSuccessfulLogin(AuthControllerTest.java:285)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

signature_generator.example.signature_generator.controller.AuthControllerTest.shouldSuccessfullyLoginVerifiedUserWithCorrectCredentials -- Time elapsed: 0.002 s <<< ERROR!
org.mockito.exceptions.misusing.PotentialStubbingProblem: 

Strict stubbing argument mismatch. Please check:
 - this invocation of 'buildToken' method:
    jwtService.buildToken(
    "test@example.com",
    1L
);
    -> at signature_generator.example.signature_generator.auth.controller.AuthController.login(AuthController.java:126)
 - has following stubbing(s) with different arguments:
    1. jwtService.buildToken("testuser", 1L);
      -> at signature_generator.example.signature_generator.controller.AuthControllerTest.shouldSuccessfullyLoginVerifiedUserWithCorrectCredentials(AuthControllerTest.java:193)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at signature_generator.example.signature_generator.auth.service.JwtService.buildToken(JwtService.java:26)
	at signature_generator.example.signature_generator.auth.controller.AuthController.login(AuthController.java:126)
	at signature_generator.example.signature_generator.controller.AuthControllerTest.shouldSuccessfullyLoginVerifiedUserWithCorrectCredentials(AuthControllerTest.java:196)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

signature_generator.example.signature_generator.controller.AuthControllerTest.shouldSendVerificationEmailAfterSuccessfulRegistration -- Time elapsed: 0.002 s <<< FAILURE!
Wanted but not invoked:
userService.registerUser(
    "newuser",
    "password123",
    "newuser@example.com",
    "1234567890"
);
-> at signature_generator.example.signature_generator.auth.service.UserService.registerUser(UserService.java:22)

However, there was exactly 1 interaction with this mock:
userService.registerUser(
    "newuser@example.com",
    "password123",
    "newuser@example.com",
    "1234567890"
);
-> at signature_generator.example.signature_generator.auth.controller.AuthController.register(AuthController.java:36)


	at signature_generator.example.signature_generator.auth.service.UserService.registerUser(UserService.java:22)
	at signature_generator.example.signature_generator.controller.AuthControllerTest.shouldSendVerificationEmailAfterSuccessfulRegistration(AuthControllerTest.java:120)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

